# Author section: applies to all Hugo themes
facebook: " https://facebook.com/example"
twitter: " https://twitter.com/example"
email: "contact@example.com"
name: "Acme Corporation"
location: Boston
phone: (999) 999-9999