baseURL: http://example.org/  # Your website location
languageCode: en-us   
title: Acme Corportaion       # Website name
theme: Eclectic               # Name of directory that holds the theme

# Author section: applies to all Hugo themes
author:
  facebook: " https://facebook.com/example"
  twitter: " https://twitter.com/example"
  email: "contact@example.com"
  name: "Acme Corporation"
  location: Boston
  phone: (999) 999-9999

# Hugo menu definitions are common across themes
menu:
  main: 
    - identifier: about 
      name: About 
      url: /about 
      weight: 100 
    - identifier: contact 
      name: Contact 
      url: /contact 
      weight: 200

# Theme-specific parameters
params: 
  color: "#4f46e5"
  copyright: "Copyright &copy; 2022 Acme Corporation.
    All Rights Reserved."
  footer:
  - title: About
    content: >
      Acme Corporation is the world's leading
      manufacturer of digital shapes. From squares and
      circles to triangles and hexagons, we have it
      all. Browse through our collection of various
      forms with different thicknesses and line styles.
      We shape the world. You live in it.


  - title: Recent Blog Posts
    recents: blog
    recentCount: 7
  - title: Contact Us
    contact: true
      